# Generated by Django 5.0.6 on 2024-09-02 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0005_alter_businessprofile_business_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscortProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('services', models.TextField()),
                ('pricing', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='escort_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='escort_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='escort_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escort_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EscortRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('escort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='escorts.escortprofile')),
                ('escort_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escort_business', to='business.businessprofile')),
            ],
        ),
    ]
