# Generated by Django 5.0.6 on 2024-07-10 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='business_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesslocation',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='business.businessprofile'),
        ),
        migrations.AddField(
            model_name='businessroles',
            name='role_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_roles', to='business.businessprofile'),
        ),
        migrations.AddField(
            model_name='businessstaff',
            name='assigned_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessstaff',
            name='staff_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_role', to='business.businessroles'),
        ),
        migrations.AddField(
            model_name='rolespermissions',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='business.businessroles'),
        ),
        migrations.AddField(
            model_name='rolespermissions',
            name='roles_permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles_permissions', to='business.generalpermissions'),
        ),
    ]
