# Generated by Django 5.0.6 on 2024-07-22 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=255)),
                ('status_description', models.CharField(max_length=255)),
                ('status_color', models.CharField(blank=True, choices=[('danger', 'Red'), ('warning', 'Yellow')], max_length=10, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('status_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_business', to='business.businessprofile')),
            ],
        ),
    ]
