# Generated by Django 5.0.6 on 2024-08-13 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_businessorderstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentActiveBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.CharField(blank=True, choices=[('On', 'On'), ('Off', 'Off')], max_length=10, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('businesses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='business.businessprofile')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
