# Generated by Django 5.0.6 on 2024-12-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_businesslocation_location_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesslocation',
            name='staff_assigned',
        ),
        migrations.AddField(
            model_name='businesslocation',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='location_type',
            field=models.CharField(choices=[('Around Business', 'Around Business'), ('Not Around Business', 'Not Around Business')], default='Around Business', max_length=50),
        ),
    ]
