# Generated by Django 5.0.6 on 2024-12-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_remove_businesslocation_staff_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessroles',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
