# Generated by Django 5.0.6 on 2024-12-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_businessroles_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='business_type',
            field=models.CharField(blank=True, choices=[('We provide accomodation', 'We provide accomodation'), ('We do not provide accomodation', 'We do not provide accomodation')], max_length=255, null=True),
        ),
    ]
