# Generated by Django 5.0.6 on 2024-07-11 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0002_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='business',
            new_name='business_c',
        ),
    ]
