# Generated by Django 5.0.6 on 2024-08-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0008_order_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
