# Generated by Django 5.0.6 on 2024-08-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0009_order_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='counter_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivered_by',
        ),
    ]
