# Generated by Django 5.0.6 on 2024-08-05 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_businessorderstatus'),
        ('ecomerce', '0010_remove_order_counter_by_remove_order_delivered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='counter_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_by', to='business.businessstaff'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivered_by', to='business.businessstaff'),
        ),
    ]
