# Generated by Django 5.0.6 on 2024-09-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0017_remove_stockpurchase_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpurchase',
            name='total_operation_costs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockpurchase',
            name='purchase_number',
            field=models.CharField(default='000000', max_length=10, unique=True),
        ),
    ]
