# Generated by Django 5.0.6 on 2024-09-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0018_stockpurchase_total_operation_costs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpurchase',
            name='purchase_number',
            field=models.CharField(default='000000', max_length=10),
        ),
    ]
