# Generated by Django 5.0.6 on 2024-09-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0019_alter_stockpurchase_purchase_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockpurchase',
            name='purchase_number',
            field=models.CharField(default='000000', max_length=10, unique=True),
        ),
    ]
