# Generated by Django 5.0.6 on 2024-09-18 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0020_purchaseitem_expiry_date_purchaseitem_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='damage_report', to='ecomerce.stockpurchase'),
        ),
    ]
