# Generated by Django 5.0.6 on 2024-09-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0021_damagereport_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='quantity_remaining',
            field=models.IntegerField(default=0),
        ),
    ]
