# Generated by Django 5.0.6 on 2024-11-06 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_businessprofile_business_owner'),
        ('ecomerce', '0023_alter_order_status_paymentproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='business.businessorderstatus'),
        ),
    ]
