# Generated by Django 5.0.6 on 2024-11-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0024_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payement_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=20, null=True),
        ),
    ]
