# Generated by Django 5.0.6 on 2024-11-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0025_order_payement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_source',
            field=models.CharField(choices=[('Online', 'Online'), ('POS', 'POS')], default='Online', max_length=50),
        ),
    ]
