# Generated by Django 5.0.6 on 2024-11-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0026_order_order_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproof',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('visa', 'Credit Card (Visa)'), ('mastercard', 'Credit Card (Mastercard)'), ('paypal', 'Paypal')], default='Cash on Delivery', max_length=50),
        ),
    ]
