# Generated by Django 5.0.6 on 2024-11-11 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0027_paymentproof_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount_paid',
            new_name='total_paid',
        ),
    ]
