# Generated by Django 5.0.6 on 2024-11-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0029_remove_order_balance_remove_order_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproof',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
