# Generated by Django 5.0.6 on 2024-11-12 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_businesslocation_location_type_and_more'),
        ('ecomerce', '0030_paymentproof_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received')], default='Pending', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='business.businesslocation')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='ecomerce.order')),
                ('recieved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_by', to='business.businessstaff')),
            ],
        ),
    ]
