# Generated by Django 5.0.6 on 2024-12-22 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0032_products_minimum_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagereport',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='ecomerce.purchaseitem'),
        ),
    ]
